In [1]:
# conda environment (project)
# /home/student/.conda/envs/project/bin/python 
%load_ext autoreload
%autoreload 2
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
import os, gc
import torch

from transformers import set_seed
from datasets import load_dataset
from evaluate import *
from arc.arc_new import ARCSolver

from datasets import Dataset
from utils import render_grid

In [2]:
# prepare the test dataset
data_path = "/workspace/dataset"
dataset, task_list = load_data(data_path)
df300 = sample_data(dataset, task_list, n_row=30000) 
df300.head(5) 

Imported 300 different tasks in the dataset.
# of samples in a task: min(82), Q1(1000), Q2(1000), Q3(1000), max(1000), mean(897.7)


task                                              train  \
0  6d58a25d  [{'input': [[2, 7, 7, 7, 7, 0, 0], [2, 7, 7, 7...   
1  b0c4d837  [{'input': [[4, 4, 4, 4, 4, 4, 4, 4, 2, 5], [4...   
2  746b3537  [{'input': [[9, 2], [3, 4], [4, 3], [3, 3], [4...   
3  25d8a9c8  [{'input': [[7, 7, 7, 7, 7, 7, 7, 7, 7, 7], [7...   
4  25ff71a9  [{'input': [[8, 2, 9, 9, 9], [9, 9, 9, 9, 9], ...   

                                          test_input  \
0  [{'input': [[5, 5, 5, 5, 5, 5, 2], [5, 5, 5, 5...   
1  [{'input': [[1, 1, 4, 4, 4, 4, 4], [9, 1, 4, 4...   
2  [{'input': [[3], [3], [7], [7], [8], [3], [7],...   
3  [{'input': [[2, 3, 3, 3, 3, 2, 3, 3, 3], [3, 2...   
4  [{'input': [[6, 6, 6, 6, 6, 1, 6, 6, 6, 6], [6...   

                                         test_output  \
0  [[[5, 5, 5, 8, 5, 5, 2], [5, 5, 5, 8, 5, 5, 2]...   
1  [[[1, 1, 2, 3, 9, 1, 2], [9, 1, 2, 3, 9, 1, 2]...   
2     [[[3, 7, 8], [3, 7, 0], [3, 7, 0], [3, 0, 0]]]   
3  [[[2, 7, 7, 7, 7, 2], [2, 2, 3, 3, 3, 3], [3, ...   
4  [[[2, 0, 6, 4, 6, 1, 6, 6, 6, 6], [7, 1, 6, 1,...   

                                                test  
0  [{'input': [[5, 5, 5, 5, 5, 5, 2], [5, 5, 5, 5...  
1  [{'input': [[1, 1, 4, 4, 4, 4, 4], [9, 1, 4, 4...  
2  [{'input': [[3], [3], [7], [7], [8], [3], [7],...  
3  [{'input': [[2, 3, 3, 3, 3, 2, 3, 3, 3], [3, 2...  
4  [{'input': [[6, 6, 6, 6, 6, 1, 6, 6, 6, 6], [6...

In [4]:
# prepare samples for each task
task_samples = []
for t in range(300):
    df = sample_data(dataset, task_list, n_row=1000, indices=[t])
    task_samples.append(df)

In [6]:
# Visualize a task (EDA)
task_idx = 11 # select which task you want to examine
n_sample = 1
for task_idx in hard_tasks[:50]:
    print(task_idx)
    for data in Dataset.from_pandas(task_samples[task_idx]).shuffle().select(range(n_sample)):
        for case in data['train']:
            print("==================================================")
            print("Example input")
            render_grid(case['input'])
            print("Example output")
            render_grid(case['output'])
            break
        print("==================================================")
        print("Example test input")
        render_grid(data['test'][0]['input'])
        print("Example test output")
        render_grid(data['test'][0]['output'])
    print("==================================================")

5
Example input


                [4, 4, 4, 4, 4, 4, 4]
                [4, 0, 4, 4, 4, 4, 4]
                [4, 0, 4, 4, 4, 4, 4]
                [4, 4, 0, 0, 4, 4, 4]
                [4, 4, 4, 0, 0, 4, 4]
                [4, 4, 0, 4, 4, 4, 4]
                [4, 4, 4, 4, 4, 4, 4]

Example output


                  [0, 0, 4, 4, 4, 4, 4, 4]
                  [0, 0, 4, 4, 4, 4, 4, 4]
                  [0, 0, 4, 4, 4, 4, 4, 4]
                  [0, 0, 4, 4, 4, 4, 4, 4]
                  [4, 4, 0, 0, 0, 0, 4, 4]
                  [4, 4, 0, 0, 0, 0, 4, 4]
                  [4, 4, 4, 4, 0, 0, 0, 0]
                  [4, 4, 4, 4, 0, 0, 0, 0]
                  [4, 4, 0, 0, 4, 4, 4, 4]
                  [4, 4, 0, 0, 4, 4, 4, 4]

Example test input


        [3, 3, 3]
        [3, 3, 3]
        [3, 3, 4]
        [3, 4, 3]
        [3, 4, 3]
        [3, 3, 3]
        [3, 3, 3]

Example test output


          [3, 3, 4, 4]
          [3, 3, 4, 4]
          [4, 4, 3, 3]
          [4, 4, 3, 3]
          [4, 4, 3, 3]
          [4, 4, 3, 3]

6
Example input


          [2, 2, 6, 5]

Example output


          [2, 2, 6, 5]
          [2, 2, 2, 6]

Example test input


              [0, 0, 0, 1, 4, 4]

Example test output


              [0, 0, 0, 1, 4, 4]
              [0, 0, 0, 0, 1, 4]
              [0, 0, 0, 0, 0, 1]

8
Example input


                      [1, 3, 1, 2, 2, 2, 2, 2, 2, 2]
                      [2, 3, 1, 2, 2, 2, 2, 2, 2, 2]
                      [2, 1, 3, 1, 2, 2, 2, 2, 2, 2]
                      [2, 2, 3, 1, 2, 2, 2, 2, 2, 2]

Example output


                      [1, 3, 1, 2, 2, 2, 2, 2, 2, 2]
                      [2, 3, 1, 2, 2, 2, 2, 2, 2, 2]
                      [2, 1, 3, 1, 2, 2, 2, 2, 2, 2]
                      [2, 2, 3, 1, 2, 2, 2, 2, 2, 2]
                      [2, 2, 1, 3, 1, 2, 2, 2, 2, 2]
                      [2, 2, 2, 3, 1, 2, 2, 2, 2, 2]
                      [2, 2, 2, 1, 3, 1, 2, 2, 2, 2]
                      [2, 2, 2, 2, 3, 1, 2, 2, 2, 2]
                      [2, 2, 2, 2, 1, 3, 1, 2, 2, 2]
                      [2, 2, 2, 2, 2, 3, 1, 2, 2, 2]

Example test input


                    [7, 7, 7, 7, 7, 7, 7, 7, 9]
                    [7, 7, 7, 7, 7, 7, 7, 9, 7]
                    [7, 7, 7, 7, 7, 7, 9, 7, 7]
                    [7, 7, 7, 7, 7, 9, 7, 7, 7]
                    [7, 7, 7, 7, 9, 7, 7, 7, 7]

Example test output


                    [7, 7, 7, 7, 7, 7, 7, 7, 9]
                    [7, 7, 7, 7, 7, 7, 7, 9, 7]
                    [7, 7, 7, 7, 7, 7, 9, 7, 7]
                    [7, 7, 7, 7, 7, 9, 7, 7, 7]
                    [7, 7, 7, 7, 9, 7, 7, 7, 7]
                    [7, 7, 7, 9, 7, 7, 7, 7, 7]
                    [7, 7, 9, 7, 7, 7, 7, 7, 7]
                    [7, 9, 7, 7, 7, 7, 7, 7, 7]
                    [9, 7, 7, 7, 7, 7, 7, 7, 7]
                    [7, 7, 7, 7, 7, 7, 7, 7, 7]

12
Example input


                  [0, 0, 0, 0, 0, 0, 0, 0]
                  [0, 0, 0, 0, 0, 0, 0, 1]
                  [7, 1, 0, 0, 0, 0, 0, 0]

Example output


        [2, 2, 0]
        [0, 0, 0]
        [0, 0, 0]

Example test input


              [4, 0, 1, 4, 4, 4]
              [1, 4, 9, 4, 0, 4]
              [1, 8, 4, 9, 4, 4]
              [9, 4, 4, 0, 4, 0]
              [0, 4, 9, 4, 9, 8]
              [9, 4, 4, 4, 9, 4]

Example test output


        [2, 2, 2]
        [4, 4, 4]
        [4, 4, 4]

15
Example input


                [9, 9, 9, 9, 9, 9, 9]
                [9, 9, 9, 9, 9, 9, 9]
                [9, 9, 9, 9, 9, 9, 9]
                [9, 4, 4, 4, 4, 4, 9]
                [9, 4, 4, 7, 7, 4, 9]
                [9, 4, 4, 4, 4, 4, 9]
                [9, 9, 9, 9, 9, 9, 9]
                [9, 9, 9, 9, 9, 9, 9]

Example output


            [9, 9, 9, 9, 9]
            [9, 4, 4, 4, 9]
            [9, 4, 7, 4, 9]
            [9, 4, 4, 4, 9]
            [9, 9, 9, 9, 9]

Example test input


            [1, 1, 1, 1, 1]
            [1, 1, 1, 1, 1]
            [1, 1, 1, 1, 1]
            [1, 1, 1, 1, 1]
            [1, 1, 1, 1, 1]
            [1, 1, 1, 1, 1]
            [1, 1, 1, 1, 1]
            [1, 1, 1, 1, 1]
            [1, 7, 7, 7, 1]
            [1, 1, 1, 1, 1]

Example test output


        [1, 1, 1]
        [1, 7, 1]
        [1, 1, 1]

19
Example input


              [5, 5, 9, 3, 3, 3]
              [9, 9, 9, 3, 3, 5]

Example output


        [5, 5, 5]
        [5, 5, 5]

Example test input


            [4, 4, 4, 4, 4]
            [4, 4, 4, 4, 8]
            [8, 4, 4, 4, 8]
            [8, 4, 8, 4, 4]
            [8, 8, 8, 8, 8]
            [8, 9, 8, 9, 8]
            [9, 8, 8, 8, 9]
            [8, 8, 9, 8, 8]

Example test output


            [8, 8, 8, 8, 8]
            [8, 8, 8, 8, 2]
            [8, 8, 8, 8, 8]
            [2, 8, 8, 8, 8]

28
Example input


      [1, 8]
      [4, 1]
      [1, 4]
      [1, 4]
      [1, 8]

Example output


          [1, 8, 8, 1]
          [4, 1, 1, 4]
          [1, 4, 4, 1]
          [1, 4, 4, 1]
          [1, 8, 8, 1]
          [1, 8, 8, 1]
          [1, 4, 4, 1]
          [1, 4, 4, 1]
          [4, 1, 1, 4]
          [1, 8, 8, 1]

Example test input


      [7, 7]
      [6, 6]
      [7, 6]
      [2, 6]
      [2, 2]

Example test output


          [7, 7, 7, 7]
          [6, 6, 6, 6]
          [7, 6, 6, 7]
          [2, 6, 6, 2]
          [2, 2, 2, 2]
          [2, 2, 2, 2]
          [2, 6, 6, 2]
          [7, 6, 6, 7]
          [6, 6, 6, 6]
          [7, 7, 7, 7]

35
Example input


          [4, 4, 4, 4]
          [4, 4, 4, 4]
          [4, 4, 4, 4]
          [4, 7, 4, 4]

Example output


                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [7, 7, 7, 7, 4, 4, 4, 4]
                  [7, 7, 7, 7, 4, 4, 4, 4]
                  [7, 7, 7, 7, 4, 4, 4, 4]
                  [7, 7, 7, 7, 4, 4, 4, 4]

Example test input


          [4, 4, 4, 4]
          [4, 4, 4, 4]
          [4, 4, 4, 4]
          [4, 4, 4, 4]

Example test output


                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]

36
Example input


      [9, 9]
      [9, 9]
      [9, 4]
      [9, 9]

Example output


          [9, 8, 9, 8]
          [9, 8, 9, 8]
          [9, 4, 9, 4]
          [9, 8, 9, 8]
          [9, 8, 9, 8]
          [9, 8, 9, 8]
          [9, 4, 9, 4]
          [9, 8, 9, 8]

Example test input


          [9, 9, 9, 9]
          [5, 9, 9, 9]

Example test output


                  [8, 9, 9, 9, 8, 9, 9, 9]
                  [5, 9, 9, 9, 5, 9, 9, 9]
                  [8, 9, 9, 9, 8, 9, 9, 9]
                  [5, 9, 9, 9, 5, 9, 9, 9]

37
Example input


                    [4, 4, 4, 4, 2, 3, 3, 3, 3]
                    [4, 2, 2, 4, 2, 3, 2, 2, 3]
                    [4, 2, 2, 4, 2, 3, 2, 2, 3]
                    [4, 4, 4, 4, 2, 3, 3, 3, 3]

Example output


      [8, 8]
      [8, 8]

Example test input


                    [5, 5, 5, 5, 8, 7, 7, 7, 7]
                    [5, 5, 5, 5, 8, 7, 7, 7, 7]
                    [5, 5, 5, 5, 8, 7, 8, 8, 7]
                    [5, 5, 5, 5, 8, 7, 8, 8, 7]

Example test output


      [2, 2]
      [4, 4]

41
Example input


        [8, 9, 8]
        [8, 8, 8]
        [8, 8, 8]
        [8, 8, 8]
        [1, 1, 1]
        [0, 9, 0]
        [9, 0, 0]
        [9, 0, 0]
        [0, 0, 0]

Example output


        [9, 3, 9]
        [9, 9, 9]
        [9, 9, 9]
        [9, 9, 9]

Example test input


                    [0, 0, 0, 9, 0, 0, 0, 0, 0]
                    [0, 0, 0, 0, 0, 0, 0, 9, 0]
                    [0, 9, 0, 0, 0, 0, 0, 9, 0]
                    [0, 0, 0, 0, 0, 0, 0, 0, 0]
                    [1, 1, 1, 1, 1, 1, 1, 1, 1]
                    [9, 9, 9, 9, 9, 9, 9, 9, 9]
                    [9, 9, 9, 9, 5, 9, 9, 9, 9]
                    [9, 9, 5, 9, 5, 5, 9, 9, 9]
                    [9, 9, 9, 9, 9, 9, 9, 9, 9]

Example test output


                    [9, 9, 9, 3, 9, 9, 9, 9, 9]
                    [9, 9, 9, 9, 9, 9, 9, 3, 9]
                    [9, 3, 9, 9, 9, 9, 9, 3, 9]
                    [9, 9, 9, 9, 9, 9, 9, 9, 9]

44
Example input


            [7, 1, 0, 1, 6]
            [1, 3, 2, 1, 1]
            [1, 0, 7, 7, 1]
            [8, 1, 1, 1, 1]
            [1, 1, 1, 1, 4]
            [1, 2, 1, 1, 5]

Example output


        [0, 1, 6]
        [2, 1, 1]
        [7, 7, 1]

Example test input


                [4, 4, 5, 4, 4, 7, 4]
                [0, 3, 3, 9, 4, 6, 1]
                [0, 4, 1, 4, 5, 8, 4]
                [0, 8, 4, 4, 4, 7, 4]
                [4, 9, 4, 4, 2, 6, 4]
                [4, 8, 7, 6, 4, 4, 4]
                [4, 4, 4, 4, 2, 3, 4]

Example test output


        [4, 7, 4]
        [4, 6, 1]
        [5, 8, 4]

49
Example input


                    [8, 8, 8, 8, 4, 8, 8, 8, 8]
                    [8, 8, 8, 8, 4, 8, 8, 8, 8]
                    [8, 8, 8, 8, 4, 8, 8, 8, 8]
                    [8, 8, 8, 8, 4, 8, 8, 8, 8]
                    [4, 4, 4, 4, 4, 4, 4, 4, 4]
                    [8, 8, 5, 5, 4, 8, 8, 8, 8]
                    [5, 5, 5, 5, 4, 8, 8, 8, 8]
                    [5, 5, 5, 5, 4, 8, 8, 8, 8]
                    [8, 5, 5, 8, 4, 8, 8, 8, 8]

Example output


                  [8, 4, 4, 8, 8, 4, 4, 8]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [8, 8, 4, 4, 4, 4, 8, 8]
                  [8, 8, 4, 4, 4, 4, 8, 8]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [8, 4, 4, 8, 8, 4, 4, 8]

Example test input


                    [3, 3, 3, 3, 1, 3, 3, 5, 3]
                    [3, 3, 3, 3, 1, 3, 3, 3, 3]
                    [1, 1, 1, 1, 1, 1, 1, 1, 1]
                    [3, 3, 3, 3, 1, 3, 3, 3, 3]
                    [3, 3, 3, 3, 1, 3, 3, 3, 3]

Example test output


                  [3, 1, 3, 3, 3, 3, 1, 3]
                  [3, 3, 3, 3, 3, 3, 3, 3]
                  [3, 3, 3, 3, 3, 3, 3, 3]
                  [3, 1, 3, 3, 3, 3, 1, 3]

51
Example input


                [3, 3, 3, 9, 5, 5, 5]
                [3, 3, 8, 9, 8, 5, 5]
                [3, 8, 8, 9, 8, 5, 5]
                [3, 3, 3, 9, 8, 5, 5]
                [9, 9, 9, 9, 9, 9, 9]
                [8, 4, 8, 9, 8, 8, 8]
                [8, 4, 8, 9, 8, 8, 8]
                [8, 4, 8, 9, 8, 8, 8]
                [4, 8, 4, 9, 8, 8, 6]

Example output


        [3, 3, 3]
        [3, 3, 5]
        [3, 5, 5]
        [3, 3, 3]

Example test input


                [8, 8, 8, 9, 7, 7, 7]
                [8, 1, 8, 9, 7, 1, 7]
                [9, 9, 9, 9, 9, 9, 9]
                [6, 1, 6, 9, 1, 1, 1]
                [1, 6, 1, 9, 1, 1, 3]

Example test output


        [8, 8, 8]
        [8, 6, 8]

53
Example input


                [7, 7, 7, 7, 7, 7, 7]
                [7, 7, 7, 7, 0, 0, 7]
                [7, 7, 7, 7, 0, 0, 7]
                [7, 7, 7, 7, 0, 0, 7]
                [7, 7, 7, 7, 0, 0, 7]
                [7, 7, 7, 7, 0, 0, 7]
                [7, 7, 7, 7, 0, 0, 7]
                [7, 7, 7, 7, 0, 0, 7]
                [7, 7, 7, 7, 7, 7, 7]
                [7, 7, 7, 7, 7, 7, 7]

Example output


      [0, 0]
      [0, 0]
      [0, 0]
      [0, 0]
      [0, 0]
      [0, 0]
      [0, 0]

Example test input


                      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                      [1, 1, 1, 1, 1, 1, 3, 3, 3, 1]
                      [1, 1, 1, 1, 1, 1, 3, 3, 3, 1]
                      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
                      [1, 1, 1, 1, 1, 1, 1, 0, 0, 1]

Example test output


      [0, 0]

55
Example input


        [2, 0, 2]
        [2, 2, 2]
        [2, 5, 9]

Example output


                    [2, 0, 2, 0, 0, 0, 2, 0, 2]
                    [2, 2, 2, 0, 0, 0, 2, 2, 2]
                    [2, 5, 9, 0, 0, 0, 2, 5, 9]
                    [2, 0, 2, 2, 0, 2, 2, 0, 2]
                    [2, 2, 2, 2, 2, 2, 2, 2, 2]
                    [2, 5, 9, 2, 5, 9, 2, 5, 9]
                    [2, 0, 2, 0, 0, 0, 0, 0, 0]
                    [2, 2, 2, 0, 0, 0, 0, 0, 0]
                    [2, 5, 9, 0, 0, 0, 0, 0, 0]

Example test input


        [2, 9, 2]
        [2, 2, 0]

Example test output


                    [2, 9, 2, 0, 0, 0, 2, 9, 2]
                    [2, 2, 0, 0, 0, 0, 2, 2, 0]
                    [2, 9, 2, 2, 9, 2, 0, 0, 0]
                    [2, 2, 0, 2, 2, 0, 0, 0, 0]

56
Example input


              [9, 9, 8, 9, 9, 6]
              [9, 3, 9, 9, 9, 9]
              [5, 9, 9, 9, 9, 9]
              [9, 9, 9, 9, 9, 9]
              [9, 9, 9, 9, 9, 9]
              [9, 9, 9, 2, 9, 9]

Example output


        [5, 3, 8]
        [9, 6, 2]
        [9, 9, 9]

Example test input


                  [2, 2, 2, 2, 2, 1, 2, 2]
                  [2, 2, 2, 7, 2, 2, 0, 2]
                  [2, 2, 2, 2, 2, 2, 2, 2]
                  [2, 2, 3, 2, 1, 2, 2, 2]
                  [2, 0, 2, 2, 2, 2, 2, 2]

Example test output


        [0, 3, 7]
        [0, 1, 1]
        [2, 2, 2]

57
Example input


                [9, 7, 1, 5, 2, 5, 5]
                [6, 5, 0, 5, 5, 5, 8]
                [3, 5, 5, 5, 7, 1, 5]

Example output


        [5, 8, 5]
        [5, 5, 1]
        [2, 5, 7]
        [5, 5, 5]
        [1, 0, 5]
        [7, 5, 5]
        [9, 6, 3]

Example test input


                  [8, 8, 8, 9, 9, 1, 8, 8]
                  [3, 9, 1, 3, 9, 9, 8, 8]
                  [1, 8, 8, 3, 8, 8, 8, 1]
                  [8, 8, 1, 8, 8, 8, 9, 8]
                  [1, 3, 9, 9, 1, 8, 3, 8]
                  [8, 3, 9, 9, 8, 9, 1, 9]

Example test output


              [8, 8, 1, 8, 8, 9]
              [8, 8, 8, 9, 3, 1]
              [1, 9, 8, 8, 8, 9]
              [9, 9, 8, 8, 1, 8]
              [9, 3, 3, 8, 9, 9]
              [8, 1, 8, 1, 9, 9]
              [8, 9, 8, 8, 3, 3]
              [8, 3, 1, 8, 1, 8]

58
Example input


                  [4, 2, 0, 2, 2, 4, 2, 0]
                  [1, 2, 7, 2, 2, 2, 7, 1]
                  [4, 9, 2, 2, 0, 2, 2, 2]
                  [2, 7, 2, 2, 6, 0, 9, 2]

Example output


                  [4, 2, 0, 2, 2, 4, 2, 0]
                  [1, 2, 7, 2, 2, 2, 7, 1]
                  [4, 9, 2, 2, 0, 2, 2, 2]
                  [2, 7, 2, 2, 6, 0, 9, 2]
                  [2, 7, 2, 2, 6, 0, 9, 2]
                  [4, 9, 2, 2, 0, 2, 2, 2]
                  [1, 2, 7, 2, 2, 2, 7, 1]
                  [4, 2, 0, 2, 2, 4, 2, 0]

Example test input


        [2, 6, 0]

Example test output


        [2, 6, 0]
        [2, 6, 0]

62
Example input


        [5, 5, 5]
        [5, 2, 5]
        [5, 5, 9]

Example output


                    [5, 5, 5, 5, 5, 5, 5, 5, 5]
                    [5, 2, 5, 5, 2, 5, 5, 2, 5]
                    [5, 5, 9, 5, 5, 9, 5, 5, 9]
                    [5, 5, 5, 0, 0, 0, 5, 5, 5]
                    [5, 2, 5, 0, 0, 0, 5, 2, 5]
                    [5, 5, 9, 0, 0, 0, 5, 5, 9]
                    [5, 5, 5, 5, 5, 5, 0, 0, 0]
                    [5, 2, 5, 5, 2, 5, 0, 0, 0]
                    [5, 5, 9, 5, 5, 9, 0, 0, 0]

Example test input


        [7, 6, 1]
        [9, 5, 3]
        [9, 2, 9]

Example test output


                    [0, 0, 0, 0, 0, 0, 0, 0, 0]
                    [0, 0, 0, 0, 0, 0, 0, 0, 0]
                    [0, 0, 0, 0, 0, 0, 0, 0, 0]
                    [7, 6, 1, 0, 0, 0, 0, 0, 0]
                    [9, 5, 3, 0, 0, 0, 0, 0, 0]
                    [9, 2, 9, 0, 0, 0, 0, 0, 0]
                    [7, 6, 1, 0, 0, 0, 7, 6, 1]
                    [9, 5, 3, 0, 0, 0, 9, 5, 3]
                    [9, 2, 9, 0, 0, 0, 9, 2, 9]

66
Example input


                      [2, 7, 7, 7, 9, 8, 4, 8, 7, 7]
                      [7, 5, 0, 7, 7, 3, 7, 7, 1, 7]

Example output


                      [7, 5, 0, 7, 7, 3, 7, 7, 1, 7]
                      [2, 7, 7, 7, 9, 8, 4, 8, 7, 7]
                      [2, 7, 7, 7, 9, 8, 4, 8, 7, 7]
                      [7, 5, 0, 7, 7, 3, 7, 7, 1, 7]

Example test input


                  [7, 9, 9, 9, 9, 9, 9, 5]
                  [5, 9, 9, 5, 9, 8, 9, 3]
                  [4, 3, 7, 9, 9, 9, 4, 6]

Example test output


                  [4, 3, 7, 9, 9, 9, 4, 6]
                  [5, 9, 9, 5, 9, 8, 9, 3]
                  [7, 9, 9, 9, 9, 9, 9, 5]
                  [7, 9, 9, 9, 9, 9, 9, 5]
                  [5, 9, 9, 5, 9, 8, 9, 3]
                  [4, 3, 7, 9, 9, 9, 4, 6]

67
Example input


                    [1, 0, 0, 0, 0, 0, 0, 6, 9]
                    [0, 0, 4, 4, 4, 4, 9, 9, 0]
                    [0, 0, 4, 0, 0, 4, 0, 0, 0]
                    [0, 0, 4, 4, 4, 4, 0, 5, 0]
                    [0, 0, 0, 0, 0, 1, 0, 0, 0]
                    [0, 0, 0, 0, 0, 0, 0, 9, 0]
                    [0, 3, 0, 2, 0, 0, 0, 0, 1]
                    [0, 0, 0, 6, 0, 0, 0, 0, 6]

Example output


      [0, 0]

Example test input


              [7, 0, 8, 4, 0, 9]
              [0, 0, 7, 6, 6, 6]
              [8, 8, 7, 6, 0, 6]
              [2, 7, 4, 6, 6, 6]

Example test output


    [0]

70
Example input


      [0, 0]
      [0, 8]
      [0, 0]
      [0, 8]
      [0, 8]
      [0, 8]
      [8, 8]
      [0, 8]
      [0, 0]

Example output


                [8, 8, 8, 8, 8, 8, 8]

Example test input


                [0, 0, 0, 0, 0, 6, 0]
                [0, 6, 0, 6, 0, 0, 0]
                [6, 0, 0, 0, 0, 0, 6]

Example test output


            [6, 6, 6, 6, 6]

78
Example input


                  [9, 9, 7, 1, 6, 7, 6, 6]
                  [9, 6, 7, 6, 6, 7, 6, 6]
                  [9, 9, 7, 6, 6, 7, 3, 6]
                  [9, 9, 7, 6, 6, 7, 6, 6]
                  [9, 9, 7, 6, 6, 7, 6, 6]
                  [9, 9, 7, 6, 6, 7, 6, 6]
                  [9, 9, 7, 6, 6, 7, 6, 6]
                  [9, 9, 7, 1, 6, 7, 6, 6]

Example output


      [9, 9]
      [9, 6]
      [9, 9]
      [9, 9]
      [9, 9]
      [9, 9]
      [9, 9]
      [9, 9]

Example test input


                  [0, 0, 7, 6, 6, 7, 6, 9]
                  [0, 0, 7, 6, 6, 7, 6, 6]
                  [0, 0, 7, 6, 6, 7, 6, 6]
                  [0, 6, 7, 6, 6, 7, 9, 9]
                  [0, 0, 7, 6, 6, 7, 9, 9]
                  [0, 6, 7, 5, 6, 7, 9, 9]
                  [0, 6, 7, 6, 6, 7, 9, 9]
                  [0, 0, 7, 6, 6, 7, 6, 6]

Example test output


      [0, 0]
      [0, 0]
      [0, 0]
      [0, 9]
      [0, 0]
      [0, 9]
      [0, 9]
      [0, 0]

80
Example input


                  [3, 3, 9, 3, 3, 3, 3, 3]
                  [3, 3, 9, 3, 3, 3, 3, 3]
                  [3, 3, 9, 3, 3, 3, 3, 3]
                  [1, 1, 9, 1, 1, 1, 1, 1]
                  [3, 3, 9, 3, 3, 3, 3, 3]
                  [3, 3, 9, 3, 3, 3, 3, 3]
                  [3, 3, 9, 3, 3, 3, 3, 3]
                  [0, 0, 9, 0, 0, 0, 0, 0]
                  [3, 3, 9, 3, 3, 3, 3, 3]

Example output


      [3, 3]
      [3, 3]
      [3, 3]

Example test input


                [5, 5, 5, 2, 5, 7, 5]
                [9, 9, 9, 2, 9, 7, 9]
                [5, 5, 5, 2, 5, 7, 5]
                [7, 7, 7, 2, 7, 7, 7]
                [5, 5, 5, 2, 5, 7, 5]
                [5, 5, 5, 2, 5, 7, 5]

Example test output


        [5, 5, 5]
        [5, 5, 5]
        [5, 5, 5]

81
Example input


      [5, 5]
      [9, 9]

Example output


          [5, 5, 9, 5]
          [9, 9, 9, 5]
          [5, 9, 9, 9]
          [5, 9, 5, 5]

Example test input


          [9, 9, 1, 1]
          [9, 1, 1, 9]
          [1, 9, 1, 1]
          [9, 9, 9, 9]

Example test output


                  [9, 9, 1, 1, 9, 1, 9, 9]
                  [9, 1, 1, 9, 9, 9, 1, 9]
                  [1, 9, 1, 1, 9, 1, 1, 1]
                  [9, 9, 9, 9, 9, 1, 9, 1]
                  [1, 9, 1, 9, 9, 9, 9, 9]
                  [1, 1, 1, 9, 1, 1, 9, 1]
                  [9, 1, 9, 9, 9, 1, 1, 9]
                  [9, 9, 1, 9, 1, 1, 9, 9]

82
Example input


        [7, 7, 6]
        [5, 7, 6]
        [6, 6, 6]

Example output


                    [6, 6, 6, 6, 7, 7, 7, 7, 6]
                    [6, 6, 6, 6, 7, 7, 7, 7, 6]
                    [6, 6, 6, 6, 7, 7, 7, 7, 6]
                    [6, 6, 6, 6, 7, 7, 7, 7, 6]
                    [7, 7, 7, 7, 6, 6, 6, 6, 6]
                    [7, 7, 7, 7, 6, 6, 6, 6, 6]
                    [7, 7, 7, 7, 6, 6, 6, 6, 6]
                    [7, 7, 7, 7, 6, 6, 6, 6, 6]
                    [6, 6, 6, 6, 6, 6, 6, 6, 6]

Example test input


        [0, 0, 0]
        [1, 9, 0]
        [1, 1, 0]

Example test output


                    [0, 0, 0, 0, 0, 0, 0, 0, 0]
                    [0, 0, 0, 0, 1, 1, 1, 1, 0]
                    [0, 0, 0, 0, 1, 1, 1, 1, 0]
                    [0, 0, 0, 0, 1, 1, 1, 1, 0]
                    [0, 0, 0, 0, 1, 1, 1, 1, 0]
                    [1, 1, 1, 1, 0, 0, 0, 0, 0]
                    [1, 1, 1, 1, 0, 0, 0, 0, 0]
                    [1, 1, 1, 1, 0, 0, 0, 0, 0]
                    [1, 1, 1, 1, 0, 0, 0, 0, 0]

83
Example input


          [6, 4, 4, 4]
          [4, 4, 3, 4]
          [6, 4, 3, 4]
          [1, 1, 5, 4]
          [1, 1, 4, 4]
          [1, 4, 4, 5]

Example output


      [1, 1]
      [3, 1]
      [3, 5]

Example test input


              [5, 5, 5, 8, 1, 1]
              [5, 1, 5, 1, 1, 1]
              [5, 1, 1, 1, 1, 1]
              [0, 0, 1, 1, 6, 1]
              [0, 0, 0, 1, 6, 6]
              [1, 0, 1, 1, 1, 1]

Example test output


        [8, 0, 5]
        [0, 0, 0]
        [5, 0, 1]

84
Example input


                    [7, 7, 7, 7, 7, 7, 7, 7, 7]
                    [7, 7, 2, 7, 7, 7, 2, 7, 7]
                    [8, 7, 7, 2, 7, 2, 7, 7, 8]
                    [7, 8, 8, 7, 7, 7, 8, 8, 7]
                    [7, 8, 7, 7, 7, 7, 7, 8, 7]
                    [7, 7, 7, 7, 7, 7, 7, 7, 7]

Example output


    [1]

Example test input


                [1, 8, 2, 4, 8, 8, 3]
                [1, 8, 1, 8, 1, 2, 1]
                [8, 7, 9, 4, 8, 6, 0]
                [8, 7, 9, 4, 8, 6, 0]
                [1, 8, 1, 8, 1, 2, 1]
                [1, 8, 2, 4, 8, 8, 3]

Example test output


    [1]

91
Example input


            [6, 5, 1, 5, 5]
            [1, 5, 5, 5, 5]
            [7, 5, 1, 5, 5]

Example output


            [6, 5, 1, 5, 5]
            [1, 5, 5, 5, 5]
            [7, 5, 1, 5, 5]
            [1, 5, 5, 5, 5]
            [6, 5, 1, 5, 5]
            [1, 5, 5, 5, 5]
            [7, 5, 1, 5, 5]
            [1, 5, 5, 5, 5]
            [6, 5, 1, 5, 5]

Example test input


            [4, 5, 5, 5, 8]
            [1, 1, 1, 4, 5]
            [5, 1, 5, 1, 5]

Example test output


            [4, 5, 5, 5, 8]
            [1, 1, 1, 4, 5]
            [5, 1, 5, 1, 5]
            [1, 1, 1, 4, 5]
            [4, 5, 5, 5, 8]
            [1, 1, 1, 4, 5]
            [5, 1, 5, 1, 5]
            [1, 1, 1, 4, 5]
            [4, 5, 5, 5, 8]

93
Example input


                      [2, 2, 2, 2, 2, 2, 3, 3, 3, 3]
                      [2, 2, 2, 2, 2, 2, 2, 3, 3, 3]
                      [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
                      [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

Example output


          [3, 3, 3, 3]
          [2, 3, 3, 3]

Example test input


              [9, 9, 9, 9, 9, 9]
              [9, 9, 9, 9, 9, 9]
              [9, 8, 8, 8, 9, 9]
              [9, 9, 8, 8, 9, 9]

Example test output


        [8, 8, 8]
        [9, 8, 8]

95
Example input


                  [5, 5, 4, 4, 4, 4, 0, 4]
                  [5, 5, 5, 5, 4, 0, 0, 4]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [2, 2, 2, 2, 4, 4, 3, 3]
                  [2, 2, 2, 2, 4, 3, 3, 3]
                  [4, 4, 2, 2, 4, 4, 3, 3]
                  [4, 4, 4, 4, 4, 4, 4, 4]
                  [1, 1, 1, 4, 4, 7, 7, 7]
                  [4, 1, 4, 1, 4, 4, 7, 7]

Example output


      [5, 0]
      [2, 3]
      [1, 7]

Example test input


                  [9, 9, 8, 9, 8, 5, 5, 5]
                  [8, 8, 9, 8, 8, 5, 8, 8]
                  [8, 8, 8, 8, 8, 8, 8, 8]
                  [9, 8, 8, 9, 8, 7, 7, 7]
                  [9, 9, 9, 9, 8, 7, 8, 7]
                  [9, 8, 8, 9, 8, 8, 7, 8]
                  [8, 8, 9, 8, 8, 8, 8, 7]

Example test output


      [9, 5]
      [9, 7]

98
Example input


    [1]
    [0]
    [7]
    [9]
    [7]
    [2]

Example output


      [1, 1]
      [0, 0]
      [7, 7]
      [9, 9]
      [7, 7]
      [2, 2]

Example test input


        [6, 1, 9]
        [9, 6, 9]
        [6, 6, 9]
        [1, 6, 6]
        [6, 9, 2]
        [9, 9, 9]
        [9, 1, 9]
        [9, 9, 6]
        [9, 1, 9]

Example test output


              [6, 1, 9, 6, 1, 9]
              [9, 6, 9, 9, 6, 9]
              [6, 6, 9, 6, 6, 9]
              [1, 6, 6, 1, 6, 6]
              [6, 9, 2, 6, 9, 2]
              [9, 9, 9, 9, 9, 9]
              [9, 1, 9, 9, 1, 9]
              [9, 9, 6, 9, 9, 6]
              [9, 1, 9, 9, 1, 9]

101
Example input


            [9, 8, 8, 8, 9]
            [9, 8, 8, 8, 3]
            [9, 9, 3, 3, 3]

Example output


                      [9, 9, 8, 8, 8, 8, 8, 8, 9, 9]
                      [9, 9, 8, 8, 8, 8, 8, 8, 9, 9]
                      [9, 9, 8, 8, 8, 8, 8, 8, 3, 3]
                      [9, 9, 8, 8, 8, 8, 8, 8, 3, 3]
                      [9, 9, 9, 9, 3, 3, 3, 3, 3, 3]
                      [9, 9, 9, 9, 3, 3, 3, 3, 3, 3]

Example test input


        [2, 5, 0]
        [0, 5, 2]
        [2, 5, 0]
        [0, 2, 0]

Example test output


              [2, 2, 5, 5, 0, 0]
              [2, 2, 5, 5, 0, 0]
              [0, 0, 5, 5, 2, 2]
              [0, 0, 5, 5, 2, 2]
              [2, 2, 5, 5, 0, 0]
              [2, 2, 5, 5, 0, 0]
              [0, 0, 2, 2, 0, 0]
              [0, 0, 2, 2, 0, 0]

103
Example input


                  [0, 0, 0, 0, 0, 0, 0, 0]
                  [0, 0, 0, 0, 0, 0, 0, 0]
                  [0, 0, 0, 0, 0, 0, 0, 0]
                  [0, 0, 0, 1, 4, 0, 0, 0]
                  [1, 1, 0, 4, 4, 0, 0, 0]
                  [4, 1, 0, 0, 0, 0, 0, 0]
                  [0, 0, 0, 0, 0, 0, 0, 0]
                  [0, 0, 0, 0, 0, 0, 0, 0]

Example output


      [1, 1]
      [4, 1]

Example test input


                  [3, 3, 3, 3, 3, 3, 3, 3]
                  [3, 3, 3, 3, 3, 3, 3, 3]
                  [3, 3, 6, 1, 3, 3, 3, 3]
                  [3, 3, 1, 1, 3, 3, 3, 3]
                  [3, 3, 3, 3, 3, 3, 3, 3]
                  [3, 3, 3, 3, 3, 3, 3, 3]

Example test output


      [6, 1]
      [1, 1]

104
Example input


                      [7, 7, 0, 7, 0, 0, 0, 7, 0, 0]
                      [8, 8, 0, 7, 0, 0, 0, 7, 7, 0]
                      [8, 8, 7, 0, 7, 0, 0, 7, 0, 7]
                      [0, 0, 7, 0, 0, 7, 0, 7, 7, 7]
                      [0, 0, 0, 7, 0, 0, 7, 7, 0, 0]
                      [0, 0, 0, 8, 8, 0, 0, 7, 7, 0]
                      [0, 7, 0, 8, 8, 7, 0, 0, 0, 0]

Example output


    [0]

Example test input


                [0, 0, 9, 9, 0, 4, 0]
                [0, 4, 9, 9, 0, 0, 0]
                [4, 4, 0, 0, 4, 0, 4]
                [9, 9, 0, 4, 4, 0, 0]
                [9, 9, 4, 4, 4, 4, 0]
                [0, 4, 0, 4, 0, 4, 4]

Example test output


    [4]

106
Example input


                    [9, 4, 9, 9, 7, 9, 9, 9, 9]
                    [8, 8, 8, 8, 7, 8, 8, 8, 8]
                    [9, 4, 9, 9, 7, 9, 9, 9, 9]
                    [8, 4, 9, 9, 7, 9, 9, 9, 9]
                    [8, 4, 8, 9, 7, 9, 9, 9, 8]
                    [9, 4, 9, 9, 7, 8, 9, 9, 9]
                    [5, 5, 5, 5, 7, 5, 5, 5, 5]
                    [8, 4, 8, 9, 7, 9, 8, 9, 9]
                    [9, 4, 8, 9, 7, 9, 9, 9, 9]
                    [9, 4, 9, 9, 7, 9, 9, 8, 9]

Example output


          [8, 8, 8, 7]
          [4, 8, 9, 7]
          [4, 8, 9, 7]
          [4, 8, 9, 7]
          [4, 9, 9, 7]
          [5, 5, 5, 7]

Example test input


                      [6, 6, 6, 6, 6, 2, 6, 5, 6, 6]
                      [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]
                      [6, 6, 6, 6, 6, 2, 6, 5, 6, 6]
                      [6, 6, 6, 6, 6, 2, 6, 5, 6, 6]
                      [6, 6, 6, 2, 6, 2, 6, 5, 6, 6]
                      [6, 6, 2, 6, 2, 2, 6, 5, 6, 6]
                      [6, 6, 6, 6, 2, 2, 6, 5, 6, 6]
                      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
                      [6, 6, 6, 6, 6, 2, 6, 5, 6, 6]
                      [6, 6, 6, 6, 6, 2, 6, 5, 6, 2]

Example test output


        [8, 8, 8]
        [2, 6, 5]
        [2, 6, 5]
        [2, 6, 5]
        [2, 6, 5]
        [2, 6, 5]
        [0, 0, 0]

109
Example input


              [5, 8, 1, 0, 9, 2]
              [7, 2, 1, 1, 4, 0]
              [0, 2, 0, 4, 9, 0]
              [9, 2, 3, 5, 3, 1]
              [9, 8, 8, 8, 1, 0]

Example output


                  [0, 5, 8, 1, 0, 9, 2, 0]
                  [5, 5, 8, 1, 0, 9, 2, 2]
                  [7, 7, 2, 1, 1, 4, 0, 0]
                  [0, 0, 2, 0, 4, 9, 0, 0]
                  [9, 9, 2, 3, 5, 3, 1, 1]
                  [9, 9, 8, 8, 8, 1, 0, 0]
                  [0, 9, 8, 8, 8, 1, 0, 0]

Example test input


        [2, 0, 5]
        [0, 5, 5]
        [4, 2, 0]
        [0, 5, 3]
        [3, 2, 8]
        [3, 4, 4]
        [8, 8, 8]

Example test output


            [0, 2, 0, 5, 0]
            [2, 2, 0, 5, 5]
            [0, 0, 5, 5, 5]
            [4, 4, 2, 0, 0]
            [0, 0, 5, 3, 3]
            [3, 3, 2, 8, 8]
            [3, 3, 4, 4, 4]
            [8, 8, 8, 8, 8]
            [0, 8, 8, 8, 0]

118
Example input


                    [1, 1, 1, 1, 1, 1, 1, 1, 1]
                    [1, 1, 6, 6, 6, 1, 1, 1, 1]
                    [1, 1, 6, 1, 6, 1, 1, 1, 1]
                    [1, 1, 6, 6, 6, 1, 1, 1, 1]
                    [1, 1, 1, 1, 1, 5, 5, 5, 5]
                    [1, 1, 1, 1, 1, 5, 1, 1, 1]
                    [1, 1, 1, 1, 1, 5, 1, 1, 1]
                    [1, 1, 1, 7, 1, 5, 1, 1, 1]
                    [1, 1, 1, 1, 1, 5, 5, 5, 5]

Example output


            [5, 5, 5, 5, 5]
            [5, 6, 6, 6, 5]
            [5, 6, 7, 6, 5]
            [5, 6, 6, 6, 5]
            [5, 5, 5, 5, 5]

Example test input


                  [5, 5, 5, 5, 5, 5, 5, 5]
                  [7, 7, 7, 7, 7, 5, 5, 5]
                  [7, 5, 5, 5, 7, 5, 5, 5]
                  [7, 5, 5, 5, 7, 5, 5, 5]
                  [7, 5, 5, 5, 7, 5, 5, 5]
                  [7, 7, 7, 7, 7, 5, 5, 5]
                  [5, 5, 5, 5, 0, 0, 0, 5]
                  [5, 5, 5, 5, 0, 6, 0, 5]
                  [5, 5, 5, 5, 0, 0, 0, 5]

Example test output


            [7, 7, 7, 7, 7]
            [7, 0, 0, 0, 7]
            [7, 0, 6, 0, 7]
            [7, 0, 0, 0, 7]
            [7, 7, 7, 7, 7]

120
Example input


                    [9, 3, 8, 2, 2, 5, 6, 6, 7]
                    [3, 0, 3, 2, 1, 1, 7, 8, 6]
                    [8, 3, 8, 5, 1, 5, 4, 2, 8]

Example output


        [6, 6, 7]
        [7, 8, 6]
        [4, 2, 8]

Example test input


                      [6, 8, 7, 4, 8, 7, 7, 6, 1, 3]
                      [8, 8, 5, 5, 6, 2, 3, 3, 3, 2]
                      [7, 5, 8, 8, 4, 7, 3, 7, 1, 3]
                      [4, 5, 8, 7, 1, 1, 3, 2, 3, 3]
                      [8, 6, 4, 1, 8, 3, 2, 3, 3, 7]

Example test output


            [7, 7, 6, 1, 3]
            [2, 3, 3, 3, 2]
            [7, 3, 7, 1, 3]
            [1, 3, 2, 3, 3]
            [3, 2, 3, 3, 7]

122
Example input


        [7, 7, 0]
        [0, 0, 7]

Example output


                    [7, 7, 0, 7, 7, 0, 7, 7, 0]
                    [0, 0, 7, 0, 0, 7, 0, 0, 7]
                    [0, 0, 0, 0, 0, 0, 0, 0, 0]
                    [0, 0, 0, 0, 0, 0, 0, 0, 0]
                    [0, 0, 0, 0, 0, 0, 0, 0, 0]
                    [0, 0, 0, 0, 0, 0, 0, 0, 0]

Example test input


      [7, 0]
      [0, 0]

Example test output


              [7, 0, 0, 0, 0, 0]
              [0, 0, 0, 0, 0, 0]
              [0, 0, 0, 0, 0, 0]
              [0, 0, 0, 0, 0, 0]
              [0, 0, 0, 0, 0, 0]
              [0, 0, 0, 0, 0, 0]

123
Example input


                    [5, 5, 5, 8, 8, 8, 8, 8, 8]
                    [5, 5, 5, 8, 8, 8, 8, 8, 8]
                    [5, 5, 5, 8, 8, 8, 8, 8, 8]
                    [5, 5, 5, 8, 8, 8, 8, 8, 8]
                    [5, 5, 5, 8, 8, 8, 8, 8, 8]
                    [5, 5, 5, 8, 8, 8, 8, 8, 8]
                    [8, 8, 8, 5, 5, 5, 5, 5, 5]
                    [8, 8, 8, 5, 5, 5, 5, 5, 5]
                    [8, 8, 8, 5, 5, 5, 5, 5, 5]

Example output


    [3]

Example test input


            [5, 5, 5, 5, 5]
            [8, 5, 8, 5, 5]
            [5, 8, 5, 5, 5]
            [8, 5, 8, 5, 5]

Example test output


    [2]

126
Example input


              [5, 5, 5, 8, 8, 8]
              [2, 2, 5, 8, 2, 8]

Example output


        [6, 6, 6]
        [6, 2, 6]

Example test input


              [1, 1, 1, 5, 5, 3]
              [1, 1, 1, 5, 5, 5]
              [3, 1, 3, 5, 5, 5]
              [3, 1, 1, 5, 5, 5]

Example test output


        [6, 6, 6]
        [6, 6, 6]
        [6, 6, 6]
        [6, 6, 6]

127
Example input


                [5, 5, 5, 5, 5, 5, 5]
                [5, 5, 5, 5, 5, 5, 5]
                [5, 6, 5, 5, 5, 5, 5]
                [5, 6, 6, 5, 5, 6, 5]
                [5, 6, 6, 6, 5, 6, 6]
                [6, 6, 6, 6, 6, 6, 6]
                [6, 6, 6, 6, 6, 6, 6]
                [6, 6, 6, 6, 6, 6, 6]

Example output


    [5]
    [6]

Example test input


                  [6, 6, 6, 3, 3, 3, 3, 3]
                  [6, 6, 6, 3, 3, 3, 3, 3]
                  [6, 6, 6, 3, 3, 3, 3, 3]
                  [6, 6, 6, 3, 3, 3, 3, 3]
                  [6, 6, 6, 3, 3, 3, 3, 3]
                  [6, 6, 6, 3, 3, 3, 3, 3]

Example test output


      [6, 3]

130
Example input


                  [5, 5, 5, 5, 5, 6, 6, 6]
                  [5, 5, 9, 9, 6, 6, 6, 5]

Example output


          [2, 5, 5, 5]
          [5, 5, 5, 5]

Example test input


              [3, 3, 3, 9, 6, 6]
              [3, 6, 3, 6, 6, 6]

Example test output


        [6, 6, 6]
        [6, 2, 6]

134
Example input


                  [1, 5, 1, 1, 1, 1, 7, 6]
                  [1, 5, 1, 1, 1, 1, 5, 1]
                  [0, 1, 1, 0, 7, 1, 1, 1]
                  [0, 7, 5, 1, 1, 1, 1, 1]

Example output


        [0, 5, 0]
        [5, 5, 5]
        [0, 5, 0]

Example test input


                  [1, 1, 1, 1, 1, 1, 1, 1]
                  [1, 1, 1, 1, 1, 1, 1, 1]
                  [1, 1, 1, 1, 1, 1, 1, 1]
                  [1, 1, 1, 1, 1, 1, 1, 1]
                  [1, 1, 1, 1, 1, 1, 1, 7]

Example test output


        [0, 5, 0]
        [5, 5, 5]
        [0, 5, 0]

135
Example input


                    [5, 0, 0, 0, 5, 5, 0, 0, 0]
                    [0, 0, 5, 5, 5, 5, 0, 0, 0]
                    [5, 0, 0, 5, 0, 0, 0, 0, 0]
                    [0, 0, 5, 5, 5, 0, 0, 5, 0]
                    [0, 0, 0, 0, 0, 0, 0, 0, 5]
                    [5, 5, 5, 0, 0, 0, 5, 5, 0]
                    [0, 0, 5, 0, 0, 0, 9, 9, 5]
                    [0, 5, 0, 0, 0, 5, 9, 9, 5]
                    [0, 5, 0, 5, 0, 0, 9, 9, 9]

Example output


        [0, 0, 0]
        [0, 0, 0]
        [0, 0, 9]

Example test input


              [0, 0, 5, 8, 8, 8]
              [0, 0, 0, 5, 8, 5]
              [5, 0, 0, 5, 5, 5]
              [5, 5, 5, 0, 0, 0]
              [9, 5, 5, 0, 0, 0]
              [5, 9, 5, 0, 0, 0]

Example test output


      [0, 8]
      [9, 0]

138
Example input


                  [5, 4, 4, 4, 4, 5, 0, 5]
                  [5, 5, 5, 5, 5, 5, 0, 5]
                  [5, 5, 5, 8, 5, 5, 0, 5]
                  [5, 5, 5, 8, 5, 5, 5, 5]
                  [5, 5, 8, 8, 5, 3, 5, 5]
                  [5, 5, 5, 5, 5, 3, 5, 5]
                  [5, 5, 5, 5, 5, 5, 5, 5]
                  [5, 5, 9, 5, 9, 5, 5, 5]
                  [5, 5, 9, 9, 9, 9, 9, 5]
                  [5, 5, 5, 5, 5, 5, 5, 5]

Example output


            [9, 5, 9, 5, 5]
            [9, 9, 9, 9, 9]

Example test input


                  [9, 9, 9, 9, 9, 9, 9, 9]
                  [9, 1, 9, 9, 9, 9, 9, 9]
                  [1, 1, 9, 9, 9, 9, 9, 9]
                  [9, 1, 9, 9, 2, 9, 9, 9]
                  [9, 9, 9, 9, 2, 9, 2, 2]
                  [9, 9, 9, 9, 9, 9, 2, 2]
                  [9, 9, 9, 0, 9, 9, 9, 9]
                  [9, 0, 0, 0, 9, 2, 2, 2]
                  [9, 0, 0, 9, 9, 9, 2, 2]
                  [9, 9, 9, 9, 9, 9, 2, 2]

Example test output


        [2, 2, 2]
        [9, 2, 2]
        [9, 2, 2]

143
Example input


                [0, 0, 5, 9, 9, 9, 0]
                [0, 0, 5, 5, 9, 9, 0]
                [0, 0, 5, 5, 5, 5, 0]
                [0, 0, 5, 5, 5, 5, 0]
                [0, 0, 0, 0, 0, 0, 0]
                [0, 0, 0, 0, 0, 0, 0]

Example output


          [9, 9, 9, 5]
          [9, 9, 5, 5]
          [5, 5, 5, 5]
          [5, 5, 5, 5]

Example test input


                [6, 6, 6, 6, 6, 6, 6]
                [6, 6, 6, 6, 4, 9, 9]
                [6, 6, 6, 6, 9, 9, 9]
                [6, 6, 6, 6, 4, 4, 4]
                [6, 6, 6, 6, 6, 6, 6]
                [6, 6, 6, 6, 6, 6, 6]
                [6, 6, 6, 6, 6, 6, 6]
                [6, 6, 6, 6, 6, 6, 6]

Example test output


        [9, 9, 4]
        [9, 9, 9]
        [4, 4, 4]

144
Example input


                      [8, 8, 8, 8, 8, 8, 1, 8, 0, 3]
                      [8, 5, 8, 8, 5, 8, 4, 3, 1, 2]
                      [4, 4, 7, 8, 5, 8, 8, 8, 8, 2]
                      [8, 8, 8, 8, 8, 8, 1, 8, 0, 3]
                      [8, 5, 8, 8, 5, 8, 4, 3, 1, 2]
                      [4, 4, 7, 8, 5, 8, 8, 8, 8, 2]

Example output


                      [8, 8, 8, 8, 8, 8, 1, 8, 0, 3]
                      [8, 5, 8, 8, 5, 8, 4, 3, 1, 2]
                      [4, 4, 7, 8, 5, 8, 8, 8, 8, 2]

Example test input


              [7, 4, 4, 3, 4, 4]
              [4, 4, 6, 7, 5, 4]
              [7, 4, 4, 3, 4, 4]
              [4, 4, 6, 7, 5, 4]

Example test output


              [7, 4, 4, 3, 4, 4]
              [4, 4, 6, 7, 5, 4]

In [5]:
simple_tasks = []
hard_tasks = []
for task_idx in range(300):
    check = True
    for data in Dataset.from_pandas(task_samples[task_idx]).shuffle().select(range(3)):
        for case in data['train']:
            wi, hi = len(case['input'][0]), len(case['input'])
            wo, ho = len(case['output'][0]), len(case['output'])
            if (wi!=wo) or (hi!=ho): check = False
        case = data['test'][0]
        wi, hi = len(case['input'][0]), len(case['input'])
        wo, ho = len(case['output'][0]), len(case['output'])
        if (wi!=wo) or (hi!=ho): check = False
    if check: simple_tasks.append(task_idx)
    else: hard_tasks.append(task_idx)
print(simple_tasks)

[0, 1, 2, 3, 4, 7, 9, 10, 11, 13, 14, 16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 34, 38, 39, 40, 42, 43, 45, 46, 47, 48, 50, 52, 54, 59, 60, 61, 63, 64, 65, 68, 69, 71, 72, 73, 74, 75, 76, 77, 79, 85, 86, 87, 88, 89, 90, 92, 94, 96, 97, 99, 100, 102, 105, 107, 108, 110, 111, 112, 113, 114, 115, 116, 117, 119, 121, 124, 125, 128, 129, 131, 132, 133, 136, 137, 139, 140, 141, 142, 145, 146, 147, 148, 149, 150, 152, 153, 154, 158, 162, 165, 166, 170, 173, 175, 176, 177, 179, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 193, 194, 195, 196, 197, 198, 199, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 217, 218, 220, 221, 222, 224, 225, 227, 228, 229, 230, 231, 233, 234, 236, 237, 239, 240, 241, 242, 243, 245, 246, 247, 249, 252, 255, 257, 261, 262, 263, 265, 269, 271, 275, 278, 279, 283, 284, 285, 287, 289, 294, 295, 296, 298]


In [6]:
set_seed(1234567890)
token = os.environ.get("HF_TOKEN", None)
solver = ARCSolver(model_id="Qwen/Qwen3-4B", hf_token=token)

In [9]:
# solver.prepare_train()
n_train = len(hard_tasks)*1000
n_eval = 500
dfsimple = sample_data(dataset, task_list, n_row=n_train+n_eval, indices=simple_tasks, random=56)
dfhard = sample_data(dataset, task_list, n_row=n_train+n_eval, indices=hard_tasks, random=56)
train_dataset = Dataset.from_pandas(dfsimple).select(range(n_train))
# solver.train(train_dataset)

In [7]:
n_eval = 100
solver.prepare_evaluation(select_adapter="20250604_112335") # make sure you set the right model

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [24]:
# evaluate our model (eval set)
scores = []
n_eval = 10
# scores_task = []
# for task in [15]: #range(20):
eval_dataset = Dataset.from_pandas(dfhard).select(range(n_train, n_train+n_eval)) # Dataset.from_pandas(task_samples[task]).select(range(n_eval))
for eval_data in tqdm(eval_dataset):
    print("============================================")
    print("Test input")
    render_grid(eval_data["test"][0]['input'])

    print("Predict output")
    preds = solver.predict(eval_data)
    if preds is not None: render_grid(preds)

    print("Test output")
    render_grid(eval_data["test"][0]['output'])
    print("============================================")
    if preds is None: s = 0
    else: s = check_match(preds, eval_data["test"][0]["output"])
    scores.append(s)
score = np.array(scores).mean() * 100
# scores_task.append(score)
print(f"Evaluation score: {score:.2f}", flush=True)
scores = []

# from matplotlib import pyplot as plt
# x = np.arange(20)
# plt.bar(x, scores_task)
# plt.xticks(x, list(range(20)))
# plt.show()

  0%|          | 0/10 [00:00<?, ?it/s]

Test input


          [2, 6, 6, 2]
          [2, 2, 7, 2]

Predict output
<|im_start|>system
You are an expert for solving logical puzzles. You are given some pairs of input and output as 2D grid with the same underlying spatial pattern between them. You have to logically infer the exact rule that transforms each input to the corresponding output.
<|im_end|>
<|im_start|>user
Here are the example input and output pairs from which you should learn the underlying rule to later predict the output for the given test input:
----------------------------------------
input:
6
6
6
0
6
6
6
6
output:
8888880
6666666

input:
929927
997992
output:
8888877
8888222
9999999

input:
73
33
73
47
output:
8884
8777
3333


----------------------------------------
Now, solve the following puzzle based on its input grid by applying the rules you have learned from the training data.:
----------------------------------------
input:
66
59
69
66

----------------------------------------
What is the output grid? Only provide the output grid in the form as in the example i

        [7 6 0]
        [7 6 0]
        [7 6 0]
        [7 0 0]

Test output


        [2, 6, 7]
        [2, 6, 0]
        [2, 0, 0]
        [2, 0, 0]
        [2, 0, 0]

Test input


                [7, 7, 4, 6, 6, 8, 8]
                [8, 7, 9, 7, 6, 6, 3]
                [6, 9, 4, 6, 3, 8, 7]
                [4, 3, 7, 7, 8, 7, 7]
                [9, 7, 9, 9, 3, 9, 8]

Predict output
<|im_start|>system
You are an expert for solving logical puzzles. You are given some pairs of input and output as 2D grid with the same underlying spatial pattern between them. You have to logically infer the exact rule that transforms each input to the corresponding output.
<|im_end|>
<|im_start|>user
Here are the example input and output pairs from which you should learn the underlying rule to later predict the output for the given test input:
----------------------------------------
input:
333322233
333233323
323233333
output:
151
555
151

input:
174
484
457
743
434
344
445
474
output:
555
511
511

input:
27272
21227
32277
22551
28988
19228
23179
51952
output:
151
555
151


----------------------------------------
Now, solve the following puzzle based on its input grid by applying the rules you have learned from the training data.:
----------------------------------------
input:
9848878
7797743
7946386
4667879
9966377

----------------------------------------
What is 

        [0 0 5]
        [0 0 5]
        [5 5 5]

Test output


        [0, 0, 5]
        [0, 0, 5]
        [5, 5, 5]

Test input


                    [4, 4, 4, 4, 4, 4, 4, 4, 4]
                    [4, 4, 4, 4, 4, 4, 4, 4, 4]
                    [4, 4, 9, 9, 9, 9, 9, 9, 9]
                    [4, 4, 9, 0, 0, 0, 0, 4, 4]
                    [4, 4, 9, 0, 0, 0, 0, 4, 4]
                    [4, 4, 9, 0, 0, 0, 0, 4, 4]
                    [4, 4, 9, 0, 0, 0, 0, 4, 4]
                    [4, 4, 9, 9, 9, 9, 9, 9, 9]
                    [4, 4, 4, 4, 4, 4, 4, 4, 4]
                    [4, 4, 4, 4, 4, 4, 4, 4, 4]

Predict output
<|im_start|>system
You are an expert for solving logical puzzles. You are given some pairs of input and output as 2D grid with the same underlying spatial pattern between them. You have to logically infer the exact rule that transforms each input to the corresponding output.
<|im_end|>
<|im_start|>user
Here are the example input and output pairs from which you should learn the underlying rule to later predict the output for the given test input:
----------------------------------------
input:
0001111
0001441
0001001
0001001
0001001
0000000
0000000
0000000
0000000
output:
400
400
400

input:
56566
56566
56566
56566
56566
57566
55566
66666
66666
output:
776
776
766

input:
8888888888
4444444448
8800000048
8800000048
8800000048
8800000048
4444444448
output:
888
088
088


----------------------------------------
Now, solve the following puzzle based on its input grid by applying the rules you have learned from the training data.:
----------------------------------------
inpu

          [0 0 0 0]
          [0 0 0 0]
          [0 0 0 0]

Test output


        [0, 0, 4]
        [4, 4, 4]
        [4, 4, 4]

Test input


                [2, 2, 2, 5, 0, 0, 1]
                [0, 2, 0, 5, 1, 1, 0]
                [0, 0, 0, 5, 0, 0, 1]
                [0, 0, 0, 5, 1, 0, 0]
                [0, 0, 0, 5, 1, 1, 1]
                [0, 0, 0, 5, 0, 1, 1]
                [0, 0, 0, 5, 1, 1, 0]

Predict output
<|im_start|>system
You are an expert for solving logical puzzles. You are given some pairs of input and output as 2D grid with the same underlying spatial pattern between them. You have to logically infer the exact rule that transforms each input to the corresponding output.
<|im_end|>
<|im_start|>user
Here are the example input and output pairs from which you should learn the underlying rule to later predict the output for the given test input:
----------------------------------------
input:
8335433
8835343
8335433
8835344
8835333
3385433
3335333
3835343
output:
333
633
333
636
663
636
333
333

input:
339
333
333
333
555
333
333
333
331
output:
336
333
333
336

input:
3337999
3337999
3337999
3337993
3337999
3237939
output:
666
666
666
663
666
666


----------------------------------------
Now, solve the following puzzle based on its input grid by applying the rules you have learned from the training data.:
----------------------------------------
input:
7333333
7733333


        [0 0 0]
        [3 0 3]
        [3 3 3]
        [3 3 3]
        [3 3 3]
        [3 0 0]
        [3 3 3]

Test output


        [3, 3, 0]
        [3, 0, 0]
        [0, 0, 3]
        [3, 0, 0]
        [3, 3, 3]
        [0, 3, 3]
        [3, 3, 0]

Test input


            [4, 4, 9, 8, 4]
            [4, 4, 9, 4, 4]
            [4, 0, 9, 4, 4]

Predict output
<|im_start|>system
You are an expert for solving logical puzzles. You are given some pairs of input and output as 2D grid with the same underlying spatial pattern between them. You have to logically infer the exact rule that transforms each input to the corresponding output.
<|im_end|>
<|im_start|>user
Here are the example input and output pairs from which you should learn the underlying rule to later predict the output for the given test input:
----------------------------------------
input:
27822
72822
22852
27822
22852
22822
22825
output:
24
42
42
24
42
22
24

input:
86562
88522
88522
88522
output:
44
66
66
66

input:
1111
1711
1111
1171
2222
6666
6666
6661
1666
output:
4444
4144
4441
1414


----------------------------------------
Now, solve the following puzzle based on its input grid by applying the rules you have learned from the training data.:
----------------------------------------
input:
10511
11511
11521

----------------------------------------
What is the 

        [3 3 3]
        [3 3 3]
        [3 3 3]

Test output


      [3, 4]
      [4, 4]
      [4, 3]

Test input


      [5, 5]
      [5, 5]
      [2, 5]

Predict output
<|im_start|>system
You are an expert for solving logical puzzles. You are given some pairs of input and output as 2D grid with the same underlying spatial pattern between them. You have to logically infer the exact rule that transforms each input to the corresponding output.
<|im_end|>
<|im_start|>user
Here are the example input and output pairs from which you should learn the underlying rule to later predict the output for the given test input:
----------------------------------------
input:
55555
55555
07552
75555
55555
output:
5555555555
4444444445
0755207552
7444474445
5455454555
5555555555
4444444445
0755207552
7444474445
5455454555

input:
999
999
997
999
999
output:
999999
949449
997997
949449
999999
999999
949449
997997
949449
999999

input:
2522
2222
1222
2222
output:
25222522
44444442
12221222
44444442
25222522
44444442
12221222
24242422


----------------------------------------
Now, solve the following puzzle based on its input grid by applying the rules you 

          [5 5 5 5]
          [8 8 8 8]
          [2 5 2 5]
          [8 8 8 8]
          [5 5 5 5]
          [8 8 8 8]
          [2 5 2 5]

Test output


          [5, 5, 5, 5]
          [5, 8, 5, 8]
          [2, 5, 2, 5]
          [5, 8, 5, 8]
          [5, 8, 5, 8]
          [2, 5, 2, 5]

Test input


        [0, 9, 0]
        [0, 9, 0]
        [8, 8, 8]
        [0, 0, 1]
        [1, 0, 1]

Predict output
<|im_start|>system
You are an expert for solving logical puzzles. You are given some pairs of input and output as 2D grid with the same underlying spatial pattern between them. You have to logically infer the exact rule that transforms each input to the corresponding output.
<|im_end|>
<|im_start|>user
Here are the example input and output pairs from which you should learn the underlying rule to later predict the output for the given test input:
----------------------------------------
input:
6662666
6332336
6662666
output:
999
333
999

input:
444427777
444427737
444423777
444427777
444423333
443427377
444427777
344427373
444427777
output:
9999
9939
3999
9999
3333
9339
9999
3393
9999

input:
7335444
3335444
7775443
7775434
3775344
output:
933
333
993
939
399


----------------------------------------
Now, solve the following puzzle based on its input grid by applying the rules you have learned from the training data.:
----------------------------------------
input:
83633

        [2 2 2]
        [0 0 2]
        [2 0 2]

Test output


        [0, 0, 0]
        [0, 0, 0]

Test input


                      [1, 4, 1, 0, 1, 1, 1, 1, 1, 1]
                      [1, 4, 1, 0, 1, 1, 1, 1, 1, 1]
                      [1, 4, 1, 0, 1, 1, 1, 1, 1, 1]
                      [2, 4, 2, 2, 2, 2, 2, 2, 2, 2]
                      [1, 4, 1, 0, 1, 1, 1, 1, 1, 1]
                      [1, 4, 1, 0, 1, 1, 8, 8, 8, 1]
                      [1, 4, 1, 0, 1, 1, 8, 1, 8, 1]
                      [1, 4, 1, 0, 1, 1, 8, 8, 8, 1]
                      [1, 4, 1, 0, 1, 1, 1, 1, 1, 1]

Predict output
<|im_start|>system
You are an expert for solving logical puzzles. You are given some pairs of input and output as 2D grid with the same underlying spatial pattern between them. You have to logically infer the exact rule that transforms each input to the corresponding output.
<|im_end|>
<|im_start|>user
Here are the example input and output pairs from which you should learn the underlying rule to later predict the output for the given test input:
----------------------------------------
input:
648494
670007
640404
640004
648494
633393
648494
688898
output:
000
040
000

input:
93899
93899
93899
93899
93899
11111
96669
76867
96669
73877
output:
666
686
666

input:
355555582
333366682
222262622
355566682
355555582
355555582
355555582
output:
666
626
666


----------------------------------------
Now, solve the following puzzle based on its input grid by applying the rules you have learned from the training data.:
----------------------------------------
input:
777772777
4444

        [0 0 0]
        [0 2 0]
        [0 0 0]

Test output


        [8, 8, 8]
        [8, 1, 8]
        [8, 8, 8]

Test input


        [6, 6, 6]
        [6, 6, 6]
        [4, 4, 6]
        [4, 4, 6]
        [4, 4, 6]

Predict output
<|im_start|>system
You are an expert for solving logical puzzles. You are given some pairs of input and output as 2D grid with the same underlying spatial pattern between them. You have to logically infer the exact rule that transforms each input to the corresponding output.
<|im_end|>
<|im_start|>user
Here are the example input and output pairs from which you should learn the underlying rule to later predict the output for the given test input:
----------------------------------------
input:
5555555555
5555555555
5555555555
5555555555
5555555555
5555555555
5555555555
5555556666
5555555555
output:
66666666

input:
7777777777
7777007077
7777000077
7777007077
7777000077
7777000077
7777000077
7777000077
7777777777
output:
00700070
00000000
00700070
00000000
00000000
00000000
00000000

input:
8888888888
8888888888
8888888888
8888888888
8888888888
8888888888
8888888888
8888488888
8888488888
output:
44
44


----------------------------------------
Now, solve the following puzz

      [4 4]
      [4 4]

Test output


          [4, 4, 4, 4]
          [4, 4, 4, 4]
          [4, 4, 4, 4]

Test input


          [9, 9, 9, 9]
          [3, 3, 3, 9]
          [3, 3, 3, 9]
          [8, 3, 3, 9]
          [3, 3, 3, 9]

Predict output
<|im_start|>system
You are an expert for solving logical puzzles. You are given some pairs of input and output as 2D grid with the same underlying spatial pattern between them. You have to logically infer the exact rule that transforms each input to the corresponding output.
<|im_end|>
<|im_start|>user
Here are the example input and output pairs from which you should learn the underlying rule to later predict the output for the given test input:
----------------------------------------
input:
22222
23333
23444
23333
output:
2222222222
2222222222
2203333333
2230333333
2233444444
2233444444
2230333333
2203333333

input:
371
371
377
377
333
output:
337711
337711
337711
337711
337077
330777
337777
337777
333333
333333

input:
2171
2171
2171
2111
2222
output:
22117711
22117711
22117711
22117711
22117711
22117711
22101101
22011110
22222222
22222222


----------------------------------------
Now, solve the following puzzle based on its input grid by applying the rules you have 

                      [9 9 9 9 9 9 9 9 9 9]
                      [9 3 3 3 3 3 3 3 9 9]
                      [9 3 3 3 3 3 3 3 9 9]
                      [9 3 3 3 3 3 3 3 9 9]
                      [9 3 3 3 3 3 3 3 9 9]
                      [9 3 3 3 3 3 3 3 9 9]
                      [9 3 3 8 3 3 3 3 9 9]
                      [9 3 3 3 3 3 3 3 9 9]
                      [9 9 9 9 9 9 9 9 9 9]
                      [9 9 9 9 9 9 9 9 9 9]

Test output


                  [9, 9, 9, 9, 9, 9, 9, 9]
                  [9, 9, 9, 9, 9, 9, 9, 9]
                  [3, 3, 3, 3, 3, 2, 9, 9]
                  [3, 3, 3, 3, 2, 3, 9, 9]
                  [3, 3, 3, 2, 3, 3, 9, 9]
                  [3, 3, 2, 3, 3, 3, 9, 9]
                  [8, 8, 3, 3, 3, 3, 9, 9]
                  [8, 8, 3, 3, 3, 3, 9, 9]
                  [3, 3, 2, 3, 3, 3, 9, 9]
                  [3, 3, 3, 2, 3, 3, 9, 9]

Evaluation score: 10.00
